language: php

php:
  - 5.5

env:
  - DOCTRINE_VERSION: 2.1.*
  - DOCTRINE_VERSION: 2.2.*
  - DOCTRINE_VERSION: 2.3.*
  - DOCTRINE_VERSION: 2.4.*
  - DOCTRINE_VERSION: 2.5.*@dev

before_install:
  - composer selfupdate
  - composer require --no-update doctrine/orm:${DOCTRINE_VERSION}

install:
  - composer update

script:
  - vendor/bin/phpunit

notifications:
  email: matthiasnoback@gmail.com