language: php

php:
  - 5.5

env:
  - DOCTRINE_VERSION: 2.1.*
  - DOCTRINE_VERSION: 2.2.*
  - DOCTRINE_VERSION: 2.3.*
  - DOCTRINE_VERSION: 2.4.*
  - DOCTRINE_VERSION: 2.5@dev

before_script:
  - composer selfupdate
  - composer require doctrine/orm:${DOCTRINE_VERSION}

script:
  - vendor/bin/phpunit

notifications:
  email: matthiasnoback@gmail.com