sudo: false

language: php

php:
  - 7.0
  - 7.1

env:
  - DOCTRINE_VERSION: ^2.4
  - DOCTRINE_VERSION: ^2.5

before_install:
  - composer selfupdate
  - composer require doctrine/orm:${DOCTRINE_VERSION}

script:
  - vendor/bin/phpunit
